name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.bump.outputs.bumped }}
      changed-files: ${{ steps.bump.outputs.changed-files }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - run: npm run build
    - run: npm test

  macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - run: npm run build
    - run: |
        npm run test-cover
        ./test.sh
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - run: npm run build
    - run: npm test

  release:
    if: ${{ github.ref_name == 'master' }}
    needs:
      - linux
      - macos
      - windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - run: npm run build
    - uses: prantlf/publish-release-action@v1
      with:
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
